
<div class="container">
	<form method='POST' action="<?php echo $block->getBaseUrl();?>/post/index/save">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name"name="name">
	    </div>
	    <div class="form-group">
	        <label for="organization">Content</label>
	        <input type="text" class="form-control" id="content" name="content">
	    </div>
	    <div class="form-group">
	        <label for="phone">Status</label>
	        <input type="text" class="form-control" id="status" name="status">
	    </div>
	    <button type="submit" class="" name="createbtn">Add</button>
	</form>
</div>