
<div class="container">
	<form method='POST' action="<?php echo $block->getBaseUrl();?>/post/index/save">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name" name="name" value="<?php $post = $block->getPost(); echo $post->getName();?>">
	    </div>
	    <div class="form-group">
	        <label for="organization">Content</label>
	        <input type="text" class="form-control" id="content"name="content" value="<?php if (isset($post['content'])) echo $post->getContent();?>">
	    </div>
	    <div class="form-group">
	        <label for="phone">Status</label>
	        <input type="text" class="form-control" id="status"name="status" value="<?php if (isset($post['status'])) echo $post->getStatus();?>">
	    </div>
	    <button type="submit" class="btn btn-primary" name="editbtn" value="<?php if (isset($post['post_id'])) echo $post->getId();?>">Submit</button>
	</form>
</div>